In [1]:
import pandas as pd
from functools import reduce

In [8]:
df_15 = pd.read_csv("2015_happiness.csv") 
df_16 = pd.read_csv("2016_happiness.csv") 
df_17 = pd.read_csv("2017_happiness.csv") 
df_18 = pd.read_csv("2018_happiness.csv") 
df_19 = pd.read_csv("2019_happiness.csv")

In [9]:
df_15 = df_15[['Country', 'HappinessRank', 'HappinessScore', 'Economy', 'Generosity', 'Trust', 'Health', 'Freedom']]
df_16 = df_16[['Country', 'HappinessRank', 'HappinessScore', 'Economy', 'Generosity', 'Trust', 'Health', 'Freedom']]
df_17 = df_17[['Country', 'HappinessRank', 'HappinessScore', 'Economy', 'Generosity', 'Trust', 'Health', 'Freedom']]
df_18 = df_18[['Country', 'HappinessRank', 'HappinessScore', 'Economy', 'Generosity', 'Trust', 'Health', 'Freedom']]
df_19 = df_19[['Country', 'HappinessRank', 'HappinessScore', 'Economy', 'Generosity', 'Trust', 'Health', 'Freedom']]

In [10]:
df_18

,Country,HappinessRank,HappinessScore,Economy,Generosity,Trust,Health,Freedom
0,Finland,1,7.632,1.305,0.202,0.393,0.874,0.681
1,Norway,2,7.594,1.456,0.286,0.340,0.861,0.686
2,Denmark,3,7.555,1.351,0.284,0.408,0.868,0.683
3,Iceland,4,7.495,1.343,0.353,0.138,0.914,0.677
4,Switzerland,5,7.487,1.420,0.256,0.357,0.927,0.660
...,...,...,...,...,...,...,...,...
151,Yemen,152,3.355,0.442,0.083,0.064,0.343,0.244
152,Tanzania,153,3.303,0.455,0.270,0.097,0.381,0.481
153,South Sudan,154,3.254,0.337,0.224,0.106,0.177,0.112
154,Central African Republic,155,3.083,0.024,0.218,0.038,0.010,0.305
155,Burundi,156,2.905,0.091,0.149,0.076,0.145,0.065

In [11]:
df_15.to_csv('2015_happiness.csv', encoding='utf-8', index=False)
df_16.to_csv('2016_happiness.csv', encoding='utf-8', index=False)
df_17.to_csv('2017_happiness.csv', encoding='utf-8', index=False)
df_18.to_csv('2018_happiness.csv', encoding='utf-8', index=False)
df_19.to_csv('2019_happiness.csv', encoding='utf-8', index=False)